interface PrDescriptionParams {
  storyId: string
  storyTitle: string
  agentAction: string
  diffSummary: string
  filesChanged: string[]
  boardBaseUrl?: string
}

export function buildPrDescription(params: PrDescriptionParams): string {
  const { storyId, storyTitle, agentAction, diffSummary, filesChanged, boardBaseUrl } = params

  const storyLink = boardBaseUrl
    ? `[${storyTitle}](${boardBaseUrl}/stories/${storyId})`
    : `${storyTitle} (\`${storyId}\`)`

  const fileList = filesChanged.length > 0
    ? filesChanged.map(f => `- \`${f}\``).join('\n')
    : '_No files listed_'

  return [
    `## Agent-Generated Change`,
    ``,
    `**Story:** ${storyLink}`,
    ``,
    `### Agent Action`,
    ``,
    agentAction,
    ``,
    `### Diff Summary`,
    ``,
    diffSummary,
    ``,
    `### Files Changed`,
    ``,
    fileList,
    ``,
    `---`,
    ``,
    `> This pull request was automatically generated by the Refinement Board agent pipeline.`,
    `> Story ID: \`${storyId}\``,
  ].join('\n')
}
