const { describe, test, expect, beforeEach } = require('@jest/globals')

beforeEach(() => jest.clearAllMocks())

// Inline the logic from pr-description.ts
function buildPrDescription(params) {
  const { storyId, storyTitle, agentAction, diffSummary, filesChanged, boardBaseUrl } = params

  const storyLink = boardBaseUrl
    ? `[${storyTitle}](${boardBaseUrl}/stories/${storyId})`
    : `${storyTitle} (\`${storyId}\`)`

  const fileList = filesChanged && filesChanged.length > 0
    ? filesChanged.map(f => `- \`${f}\``).join('\n')
    : '_No files listed_'

  return [
    `## Agent-Generated Change`,
    ``,
    `**Story:** ${storyLink}`,
    ``,
    `### Agent Action`,
    ``,
    agentAction,
    ``,
    `### Diff Summary`,
    ``,
    diffSummary,
    ``,
    `### Files Changed`,
    ``,
    fileList,
    ``,
    `---`,
    ``,
    `> This pull request was automatically generated by the Refinement Board agent pipeline.`,
    `> Story ID: \`${storyId}\``,
  ].join('\n')
}

describe('buildPrDescription', () => {
  const baseParams = {
    storyId: 'cmo6585or009cyojnet85ef9m',
    storyTitle: 'GitHub PR creation from agent-generated diffs',
    agentAction: 'Implemented GitService with createBranch, commitFiles, openPR methods',
    diffSummary: 'Added 3 new files, modified 1 existing file',
    filesChanged: ['src/infrastructure/github/git-service.ts', 'app/api/github/pull-requests/route.ts'],
  }

  test('includes story ID in the description', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('cmo6585or009cyojnet85ef9m')
  })

  test('includes story title in the description', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('GitHub PR creation from agent-generated diffs')
  })

  test('includes agent action in the description', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('Implemented GitService with createBranch, commitFiles, openPR methods')
  })

  test('includes diff summary in the description', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('Added 3 new files, modified 1 existing file')
  })

  test('lists changed files', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('src/infrastructure/github/git-service.ts')
    expect(result).toContain('app/api/github/pull-requests/route.ts')
  })

  test('creates board link when boardBaseUrl is provided', () => {
    const result = buildPrDescription({
      ...baseParams,
      boardBaseUrl: 'https://myapp.com',
    })
    expect(result).toContain('[GitHub PR creation from agent-generated diffs](https://myapp.com/stories/cmo6585or009cyojnet85ef9m)')
  })

  test('uses plain text story reference when boardBaseUrl is not provided', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('GitHub PR creation from agent-generated diffs (`cmo6585or009cyojnet85ef9m`)')
  })

  test('shows no files listed when filesChanged is empty', () => {
    const result = buildPrDescription({ ...baseParams, filesChanged: [] })
    expect(result).toContain('_No files listed_')
  })

  test('includes attribution footer', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('automatically generated by the Refinement Board agent pipeline')
  })

  test('includes story ID in footer', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('Story ID: `cmo6585or009cyojnet85ef9m`')
  })

  test('contains all required sections', () => {
    const result = buildPrDescription(baseParams)
    expect(result).toContain('## Agent-Generated Change')
    expect(result).toContain('### Agent Action')
    expect(result).toContain('### Diff Summary')
    expect(result).toContain('### Files Changed')
  })
})
